### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by arl03** [fdciabdul/termux-whatsapp-bot#15]
Tambahin Fitur  Admin bang
Pake:

const { WAGroupMetaData } = require ('@adiwajshing/baileys')

const metaData = await conn.groupMetaData(id)
console.log(metaData)

Informasi lengkap nya diatas.

**Comment by fdciabdul** [comment]
> Tambahin Fitur Admin bang
> Pake:
> 
> const { WAGroupMetaData } = require ('@adiwajshing/baileys')
> 
> const metaData = await conn.groupMetaData(id)
> console.log(metaData)
> 
> Informasi lengkap nya diatas.

belum ada waktu wkwk. , open commit aja kalo bisa mah

**Comment by arl03** [comment]
Ok dah bang wkwk
