### ISSUE TITLE
please answer and fix it

### ISSUE THREAD

**Issue by seanganteng** [fdciabdul/termux-whatsapp-bot#2]
![Screenshot_2020-10-20-22-56-24-594_com termux](https://user-images.githubusercontent.com/48561347/96667370-29ed6780-1383-11eb-988d-58a177627dd4.jpg)

**Comment by fdciabdul** [comment]
silahkan clone ulang , dan gausah pake ubuntu

**Comment by seanganteng** [comment]
> silahkan clone ulang , dan gausah pake ubuntu

Ok bisa jalan
