### ISSUE TITLE
Gagal Scan QR Code

### ISSUE THREAD

**Issue by Nievl06** [fdciabdul/termux-whatsapp-bot#22]
Kayanya aku yang ga paham bang, di screenshot terus scan lewat gambar kan yaa?

![Screenshot_2020-12-25-18-41-43-21_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/53964468/103134061-e0056280-46e0-11eb-97fc-7585bf99fcae.jpg)

**Comment by fdciabdul** [comment]
scan pake hp kedua
