### ISSUE TITLE
Yang work cuma stiker bang

### ISSUE THREAD

**Issue by seanganteng** [fdciabdul/termux-whatsapp-bot#4]
![Screenshot_2020-10-24-08-52-28-968_com termux](https://user-images.githubusercontent.com/48561347/97065224-5ea52d00-15d6-11eb-8718-10cb7e6690a7.jpg)

!menu ga bisa

**Comment by fdciabdul** [comment]
!menu kan emang gaada :D , nanti kalo ada waktu di tambah tambahin lagi
