### ISSUE TITLE
GK tau kenapa

### ISSUE THREAD

**Issue by akuganteng-glicth** [fdciabdul/termux-whatsapp-bot#5]
![IMG-20201025-WA0072](https://user-images.githubusercontent.com/73433094/97110441-de80e380-170b-11eb-8031-6b094db1dc1f.jpeg)
Bang kok gini ? Mau stiker ? Sama mau nyoba MP3 sama Ig GK bisa ?

**Comment by fdciabdul** [comment]
di clone lagi ya 👍
