### ISSUE TITLE
Habis update jadi begini bang

### ISSUE THREAD

**Issue by seanganteng** [fdciabdul/termux-whatsapp-bot#6]
![Screenshot_2020-10-28-11-43-09-583_com termux](https://user-images.githubusercontent.com/48561347/97396421-a18a3c00-1919-11eb-8f8f-bc1ac8a4f9f8.jpg)

**Comment by fdciabdul** [comment]
npm i image-to-base64

**Comment by seanganteng** [comment]
Oke terimakasih
